src/docs/index.md
=> fix(docs): 翻译遗漏的部分

src/blog/cost-of-javascript-2019.md
=> fix `workder` to `worker`

src/blog/wasm-decompile.md
=> 翻译 translate blog/wasm-decompile

src/docs/ignition.md
I have completed the translation of the document **docs/ignition**, thank you.
=> [Completed] translate **docs/ignition**

src/docs/turbofan.md
I have completed the translation of the **docs/turbofan** document, thank you.
=> [Completed] translate **docs/turbofan**

src/docs/index.md, src/docs/torque.md
I have completed the translation, **docs/turque.md** .
=> [Completed] start translate on docs/turque

src/docs/index.md, src/docs/profile.md
I have completed the translation, **docs/profile.md**.
=> [Completed] start translating docs/profile.md

src/docs/index.md, src/docs/profile-chromium.md
I have completed the translation, **docs/profile-chromium.md**.
=> [Completed] translation completed - docs/profile-chromium.md

src/blog/fast-super.md
I have completed the translation, **blog/fast-super.md**.
=> [Completed] translation completed - blog/fast-super.md

src/docs/index.md, src/docs/rcs.md
I have completed the translation, **docs/rcs.md**.
=> [Completed] translation completed - docs/rcs.md

src/docs/linux-perf.md
I have completed the translation, **docs/linux-perf.md**.
=> [Completed] translation completed - docs/linux-perf.md

src/docs/trace.md
I have completed the translation, **docs/trace.md**.
=> [Completed] translation completed - docs/trace.md

src/blog/adaptor-frame.md
I finished the translation, **blog/adaptor-frame.md**.
=> [Completed] Translation completed, blog/adaptor-frame.md

src/blog/high-performance-cpp-gc.md
I have completed the translation, **blog/high-performance-cpp-gc.md**.
=> [Completed] completed translation, blog/high-performance-cpp-gc.md

src/blog/free-garbage-collection.md
I have completed the translation, **blog/free-garbage-collection.md**.
=> [Completed] completed translation, blog/free-garbage-collection.md

src/blog/code-caching.md
I have completed the translation, **blog/code-caching.md**.
=> [Completed] completed translation, blog/code-caching.md

src/blog/turbofan-jit.md
I have completed the translation, **blog/turbofan-jit.md**.
=> [Completed] completed translation, blog/turbofan-jit.md

src/blog/jank-busters.md
**blog/jank-busters.md**, translation completed.
=> [Completed ] completed translation, blog/jank-busters.md

src/blog/orinoco.md
**blog/orinoco.md**, translation completed.
=> [Completed] blog/orinoco.md, translation completed

src/blog/optimizing-v8-memory.md
**/blog/optimizing-v8-memory.md**, translation completed.
=> [Completed] /blog/optimizing-v8-memory.md, translation completed

src/blog/heap-size-limit.md
**blog/heap-size-limit.md**, translation completed.
---
*V8 officially released another [blog post](https://v8.dev/blog/sparkplug) on the 27th.*
=> [Completed] blog/heap-size-limit.md, translation completed

src/blog/lazy-unlinking.md
**blog/lazy-unlinking.md**, translation completed.
=> [Completed] blog/lazy-unlinking.md, translation completed

src/blog/orinoco-parallel-scavenger.md
**blog/orinoco-parallel-scavenger.md**, translation completed.
=> [Completed] blog/orinoco-parallel-scavenger.md, translation completed

src/blog/tracing-js-dom.md
**blog/tracing-js-dom.md**, translation completed.
=> [Completed] blog/tracing-js-dom.md, translation completed

src/blog/v8-lite.md
docs: **/blog/v8-lite.md**, translation completed.
=> [Completed] /blog/v8-lite.md, translation completed.

src/blog/pointer-compression.md
**blog/pointer-compression.md**, translation completed.
=> [Completed] blog/pointer-compression.md, translation completed
